// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/validate/validate.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLChecker is a mock of URLChecker interface.
type MockURLChecker struct {
	ctrl     *gomock.Controller
	recorder *MockURLCheckerMockRecorder
}

// MockURLCheckerMockRecorder is the mock recorder for MockURLChecker.
type MockURLCheckerMockRecorder struct {
	mock *MockURLChecker
}

// NewMockURLChecker creates a new mock instance.
func NewMockURLChecker(ctrl *gomock.Controller) *MockURLChecker {
	mock := &MockURLChecker{ctrl: ctrl}
	mock.recorder = &MockURLCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLChecker) EXPECT() *MockURLCheckerMockRecorder {
	return m.recorder
}

// CheckURL mocks base method.
func (m *MockURLChecker) CheckURL(url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckURL", url)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckURL indicates an expected call of CheckURL.
func (mr *MockURLCheckerMockRecorder) CheckURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckURL", reflect.TypeOf((*MockURLChecker)(nil).CheckURL), url)
}
