services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shortener
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shortener" ]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:shortener@postgres:5432/shortener?sslmode=disable", "up" ]
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    environment:
      DATABASE_URI: "postgres://postgres:shortener@postgres:5432/shortener?sslmode=disable"
      SECRET_KEY: "t{$z]P%bwE"
    ports:
      - "8080:8080"
    depends_on:
      - migrate
